# Generated by Django 3.2.12 on 2022-04-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
