# Generated by Django 3.2.12 on 2022-03-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        ('domains', '0001_initial'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('summary', models.TextField(max_length=280, verbose_name='summary')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('year', models.IntegerField(verbose_name='year')),
                ('citizenship_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.citizenshipstatus', verbose_name='citizenship status')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain', verbose_name='domain')),
                ('keywords', models.ManyToManyField(to='keywords.Keyword', verbose_name='keywords')),
                ('tools', models.ManyToManyField(to='tools.Tool', verbose_name='tools')),
            ],
        ),
    ]
