# Generated by Django 3.2.12 on 2022-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
