# Generated by Django 3.2.12 on 2022-04-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_slug'),
        ('projects', '0002_project_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
