# Generated by Django 3.2.12 on 2022-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classtimes', '0001_initial'),
        ('projects', '0003_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='classtimes',
            field=models.ManyToManyField(to='classtimes.Classtime', verbose_name='classtimes'),
        ),
    ]
