# Generated by Django 3.2.12 on 2022-04-15 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_classtimes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenshipstatus',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
