# Generated by Django 3.2.12 on 2022-04-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220415_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
