# Generated by Django 3.2.12 on 2022-04-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_project_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['updated_at']},
        ),
    ]
