# Generated by Django 3.2.12 on 2022-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classtimes', '0002_auto_20220524_0803'),
        ('projects', '0008_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='classtimes',
        ),
        migrations.AddField(
            model_name='project',
            name='labtimes',
            field=models.ManyToManyField(to='classtimes.Labtime', verbose_name='labtimes'),
        ),
        migrations.AddField(
            model_name='project',
            name='lecturetimes',
            field=models.ManyToManyField(to='classtimes.Lecturetime', verbose_name='lecturetimes'),
        ),
    ]
