# Generated by Django 3.2.12 on 2022-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220524_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reg_status',
            field=models.BooleanField(default=False),
        ),
    ]
