# Generated by Django 3.2.12 on 2022-10-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_reg_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='reg_status',
            new_name='registration_status',
        ),
    ]
