# Generated by Django 3.2.12 on 2023-03-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_reg_status_project_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deafpods_bool',
            field=models.BooleanField(default=False, verbose_name='DEAFPODS'),
        ),
    ]
