# Generated by Django 3.2.12 on 2024-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='online_bool',
            field=models.BooleanField(default=False, verbose_name='ONLINE'),
        ),
    ]
