# Generated by Django 3.2.12 on 2024-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_online_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rockies_bool',
            field=models.BooleanField(default=False, verbose_name='ROCKIES'),
        ),
    ]
