# Generated by Django 3.2.12 on 2022-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.ManyToManyField(to='days.Day', verbose_name='days')),
            ],
        ),
    ]
