# Generated by Django 3.2.12 on 2022-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options'),
        ('days', '0001_initial'),
        ('classtimes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classtime',
            new_name='Labtime',
        ),
        migrations.CreateModel(
            name='Lecturetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.ManyToManyField(to='days.Day', verbose_name='days')),
            ],
        ),
    ]
