# Generated by Django 3.2.12 on 2022-04-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name']},
        ),
    ]
